mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
pom.xml

Signed-off-by: xiaolong.ran <rxl@apache.org>
Fixes: #21 
Currently, mop uses the 2.6.0 version, which causes compatibility problems when users use the 2.6.1 version, resulting in unavailability.
Upgrade pulsar broker version to 2.6.1

Upgrade pulsar broker version to 2.6.1

---

.github/workflows/release-note.yml
README.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MessagePublishContext.java

Fix some names that misreference AoP probably left behind when scaffolding the project.

Correct references to AoP and AMQP -> MoP and MQTT

---

pom.xml

Pulsar classes will be provided at runtime.
Not including them in the NAR reduces the archive size from ~130MB to
~5MB.

Change Pulsar dependency to be provided

---

.github/workflows/pr_test.yml
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyConnection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/ProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/PulsarTopicUtilsTest.java
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/BasicAuthenticationIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/TokenAuthenticationIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java

Adding a namespace prefix in the MQTT topic name when sending messages and subscribe to a topic.
```
|  __public/default__/a/b/c     ->      /a/b/c under public/default          |
|  __public/default__a/b/c      ->      a/b/c under public/default           |
|  __public/default__/+/b/c      ->     /+/b/c under public/default          |
|  __public/default__/a/b/#     ->      /a/b/# under public/default          |
```
Or
persistent://public/default//a/b/c It's better for us to support non-persistent topic in the future
```
|  persistent://public/default//a/b/c  ->    /a/b/c under public/default     |
|  persistent://public/default/a/b/c   ->    a/b/c under public/default      |
|  persistent://public/default//+/b/c  ->    /+/b/c under public/default     |
| …
```

Support multiple levels topic name

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyInboundHandler.java

Currently, the MoP proxy connects with the MoP broker by the method `await()`, this is a block method and it's not recommented, it may cause a deadLock exception.
```
07:17:11.254 [mqtt-redirect-io-32-1:io.streamnative.pulsar.handlers.mqtt.proxy.ProxyInboundHandler@311] ERROR io.streamnative.pulsar.handlers.mqtt.proxy.ProxyInboundHandler - [Proxy Subscribe] Failed to perform lookup request
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@51264ab4(incomplete)
at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:462) ~[netty-common-4.1.67.Final.jar:4.1.67.Final]
at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:159) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
at …
```

[Proxy] Make MoP proxy connect with MoP broker asynchronously

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ConnectionDescriptor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/ProtocolMethodProcessorImpl.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/BasicAuthenticationIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/TokenAuthenticationIntegrationTest.java

- [MQTT-3.1.4-2]: If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client.

Fix the issue with same client ID and tests.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/LookupHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyException.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java

- Rename ProxyService to MQTTProxyService.
- Rename ProxyConfiguration to MQTTProxyConfiguration.
- Rename ProxyException to MQTTProxyException.
- Rename ProxyHandler to MQTTProxyExchanger.
- Rename ProxyConnection to MQTTProxyHandler.
- Rename ProtocolMethodProcessorImpl to DefaultProtocolMethodProcessorImpl.
- Using HostAndPort instead of string host and int port.
- Add close method for LookupHandler.
- Remove unused fields and methods.
- Throw MQTTProxyException instead of Exception.
- Add print stack trace when start occurs exception.

Refactor mop proxy part

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/LookupHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java

As we define the return type of method [findBroker] as CompletableFuture which contains `exception` and `result value`.
So it's better to remove the signature of `throws Exception`
- Remove the signature of `throws Exception` for LookupHandler#findBroker.

Remove the signature of `throws Exception` for LookupHandler#findBroker

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java

As ExchangerHandler can read message type from the message, it's better to remove our own defined State ( it's useless).
- Rename BackendHandler to ExchangerHandler.
- Remove `clientChannel.close()`, as MQTTProxyProtocolMethodProcessor#writeAndFlush will do this if exception occurs.
- Remove our own define State, using message type instead.

Refactor proxy exchanger

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
pom.xml
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/hivemq/HiveMQIntegrationTest.java

Looks There are some differences between different MQTT client handling the topic name of the message that send to the client.
For the fusesource MQTT client, looks it will not check the topic name of the message, but the mqtt.fx checked.
So all the integration tests passed, but after using mqtt.fx UI tool to verify the topic name filter, the single level
topic name filter does not works.
The fix is return the original topic name to the consumer to avoid differences topic handling between different clients.
And added hiveMQ MQTT client for the integration tests.

Fix subscribe with topic filter issues

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java

`processDisconnect` should add `MqttMessage` for proxy to transform it to mqtt broker. 
- Add param `MqttMessage` for `processDisconnect`.
- Remove param `String clientID` for `processConnectionLost`.

Redefine the `processDisconnect` and `processConnectionLost` method.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java

If `channelRead` occurs error, eg: clientId is invalid, we will not get the root cause in the stack trace. See below comments.
So we should check the message decoder state before other logics.
- Add checkState for the message decoder state.
- Check clientId to avoid NPE.
- Add test cases.

Add checkState to log decoder failure instead of swallowing it.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServerConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/PulsarTopicUtilsTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java

#50 
Support config of non-persistent topic by default.
In my case,  some time i just use non-persistent for mop , i want my user use topic `topicA` not `non-persistent://public/default/topicA`.

Support nonpersistent config

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/PulsarTopicUtilsTest.java

This error Affect all topics of `[persistent/non-persistent]/{tenant}/{namespace}/{topic}`,  
Just wrong when i send message to `non-persistent://public/default/topicAAA`
TopicName.getNamespace() return `public/default`, and then the message will be send to `non-persistent://public/public/default/topicAAA` 
@codelipenghui   PTAL, Thanks.

Fix wrong topicname

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java

If mqtt broker send a bad request, proxy exchanger handler could not get the root cause. See below comment for stack trace.
- Add checkState for ExchangerHandler.
- CheckState before retrieve the messageType.

Add checkState for proxy exchanger

---

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTLSTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/TLSTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java

When proxy is enabled,  the test case only starts one broker.  It's better to start multi-brokers in a cluster.

[Test] Start multi-broker if proxy enabled.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java

If there are more MQTT clients connected to the server, and we wanna find out the special client's action, it's not clear. 
After this patch, all clientId printed to the log, and it's easy to find out.
- Print clientId to the log
- Set log to debug level, for there maybe a lot of connections.

Print clientId to the log that can be easy to find out all client actions

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java

MQTTProxyHandler and MQTTInboundHandler have the same logic to process ping request. So define a default implementation of processPingReq can reuse the logic.
- Add processPingReq to ProtocolMethodProcessor.

Add processPingReq to ProtocolMethodProcessor

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java

Netty worker group should be configurable, for different scenarios, users may set different worker threads for IO event.

Make Netty boss and worker group configurable.

---

README.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/psk/PSKConfiguration.java

After the test,  TLS PSK is only supported in TLSv1.2 currently, So update the default configuration and relative doc.
- Remove unsupported protocols.
- Add more default supported ciphers.
- Update relative doc.

Update TLS PSK default configuration.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java

#236 
Using AtomicReferenceFieldUpdater instead of AtomicReference for channelState in Connection.

Using AtomicReferenceFieldUpdater instead of AtomicReference for channelState in Connection

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/mqtt5/SessionExpireInterval.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5CleanStartTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5SessionExpireIntervalTest.java

This feature detail in MQTT5 spec 3.14.2.2.2
- Support disconnect contains session expire interval time to update connect sent value.
- Support disconnect session expire interval value check.
- Support session dose not expire when value is 0xFFFFFFFF (UINT_MAX)

Support disconnect session expire interval

---

.github/workflows/pr_test.yml
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttConnAckMessageHelper.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttUtils.java

ProtocolMethodProcessor has defined all the MQTT messages to handle. but every method contains `channel` which is reducant, we can obtain it from the constructor. So decide to remove it.
- Remove `channel` from each method in ProtocolMethodProcessor.

Refactor ProtocolMethodProcessor, remove param `channel`.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Constants.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/QosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/handler/MopExceptionHelper.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos2PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/QosPublishHandlersImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java

As we support MQTT5,  we need to bind more properties to the channel. This is not a good way.  It's better to store these properties to `connection`, and we only bind `connection` to the channel.
Another, we can get the channel at the construct time, so no need to pass the `channel` to any method, like `qos1().publish(channel, msg)`
- Move mqtt properties to connection.
- Remove the channel from publish method in qos handler.

Refactor mqtt property part, put these properties to connection.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandlerFactory.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV3xAckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV5AckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/package-info.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java

For we support mqtt5 protocol, and more properties and features added. Before this pr, we face that in every response, we need to judge if the current protocol is mqtt5 or mqtt3 to decide to return a different response .
So we involved ack handler to resolve this issue. The different protocols will use different ack handlers to process the response and avoid judging the protocol everywhere.
- Add ack handler.
- Move some properties to connection.

Add ack handler to process different protocol response.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java

There are some common methods and logics in DefaultProtocolMethodProcessorImpl and MQTTProxyProtocolMethodProcessor.
It's better to move these methods in one class and let the two classes extend it.
- Add AbstractCommonProtocolMethodProcessor.

Add AbstractCommonProtocolMethodProcessor to share some common methods.

---

pom.xml

fixed #322
Bump log4j-core from 2.13.3 to 2.16.0

[ mop 2.8 ] Bump log4j-core from 2.13.3 to 2.16.0

---

pom.xml

fixed #322
Bump log4j-core from 2.13.3 to 2.16.0

[ mop 2.7 ] Bump log4j-core from 2.13.3 to 2.16.0

---

pom.xml

fixed #322
Bump log4j-core from 2.13.3 to 2.16.0

[ mop 2.9 ] Bump log4j-core from 2.13.3 to 2.16.0

---

pom.xml

fixed #322
Bump log4j-core from 2.13.3 to 2.16.0

[ mop 2.8.1 ] Bump log4j-core from 2.13.3 to 2.16.0

---

pom.xml

https://logging.apache.org/log4j/2.x/security.html

[ 2.9 ] Upgrade log4j2 version to 2.17.0 

---

pom.xml

https://logging.apache.org/log4j/2.x/security.html

[ 2.7 ] Upgrade log4j2 version to 2.17.0 

---

pom.xml

https://logging.apache.org/log4j/2.x/security.html

[ 2.8.1 ] Upgrade log4j2 version to 2.17.0 

---

pom.xml

https://logging.apache.org/log4j/2.x/security.html

[ 2.8 ] Upgrade log4j2 version to 2.17.0 

---

README.md
docs/mop-configuration.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java

In netty decoder, default length is 8092.
```
public final class MqttDecoder extends ReplayingDecoder<MqttDecoder.DecoderState> {
private MqttFixedHeader mqttFixedHeader;
private Object variableHeader;
private int bytesRemainingInVariablePart;
private final int maxBytesInMessage;
private final int maxClientIdLength;
public MqttDecoder() {
this(8092, 23);
}
public MqttDecoder(int maxBytesInMessage) {
this(maxBytesInMessage, 23);
}
```
In some case, mqtt message length is over limit, there is a error `java.lang.IllegalStateException: too large message: 16422 bytes.`
I think we should allow user to set the max message length.
Support set message length.
Check the box below and label this PR (if you have committer privilege).

Support set message length.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServiceServlet.java

Fix #352.
Pulsar will load servlet and protocol handler with different NarClassLoader, and cause the issue.
We should call `MetricsCollector` in protocol handler classloader directly, not casting.

Fix MoP http metrics class casting issue.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyInboundHandler.java

As there are some common methods in MQTTProxyHandler and MQTTInboundHandler,  it's better to share them.
So add MQTTCommonInboundHandler
- Add MQTTCommonInboundHandler to abstract the common methods.
- Rename `MQTTProxyHandler` to `MQTTProxyInboundHandler`

Refactor mqtt inbound handler.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MessagePublishContext.java

`` ReferenceCountUtil.safeRelease(msg)`` has many judgement.
Because of we can know who is ``ReferenceCounted``, Then i think we do not need to do redundant judgement.
```java
public static void safeRelease(Object msg) {
try {
release(msg);
} catch (Throwable var2) {
logger.warn("Failed to release a message: {}", msg, var2);
}
}
```
```java
public static boolean release(Object msg) {
return msg instanceof ReferenceCounted ? ((ReferenceCounted)msg).release() : false;
}
```
- Use ``msg.release()`` to instead of  `` ReferenceCountUtil.safeRelease(msg)``

Use ``msg.release()`` to instead of  `` ReferenceCountUtil.safeRelease(msg)``

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java

Fix #380 .
Before this pr, if subscribe occurs exception, there may exist dirty data in topicCountForSequenceId. But fortunately,  MQTTProxyProtocolMethodProcessor is connection-based. If subscribe occurs exception, the connection will close, and MQTTProxyProtocolMethodProcessor is destroyed. So dirty data may not expose or cause any problem.  But this implementation is not good and may cause ambiguity. 
So when subscribe occurs exception, remove the msg-id from the topicCountForSequenceId.
- Add remove method to remove related msg-id from topicCountForSequenceId when exception.
- Rename topicCountForSequenceId to subscribeTopicsCount

Fix subscribe count exists dirty data issue

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/restrictions/InvalidReceiveMaximumException.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/restrictions/InvalidSessionExpireIntervalException.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/restrictions/package-info.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttConnectAckHelper.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ClientRestrictions.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ServerRestrictions.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/package-info.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV3xAckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV5AckHandler.java

Because of MQTT protocol version 5 have some other restrictions like ``maximum packet size``,``maximum qos``, ``retain avaliable`` etc.
I think it's a best way to refactor some previous logic.
- Add ``ClientRestriction`` store some restrictions about client side.
- Add ``ServerRestriction`` store some restrictions about server side.
- Refactor some logic implementation.

[MIP-3] Add ``Client Restriction`` and ``Server Restriction`` to make the logic clear

---

mqtt-impl/pom.xml
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
pom.xml
tests/pom.xml

https://github.com/apache/pulsar/pull/10478 introduced an API change to `MessageImpl#create`, which is included in 2.10.0.0-rc4, we need to fix the conflict.

Bump version 2.10.0.0 rc4

---

mqtt-impl/pom.xml
pom.xml
tests/pom.xml

The latest mop version is in branch 2.9.1 is 2.9.1.5, but the current version is ``2.9.0-SNAPSHOT``. so, we need to upgrade it.
- bump mop version to 2.9.1.5

Bump MOP version to 2.9.1.5

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
pom.xml

Use ``BeanUtils#copyProperties`` to copy proxy config.
- Use ``BeanUtils#copyProperties`` to copy proxy config. 

Use ``BeanUtils#copyProperties`` to copy proxy config.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ClientReceiveMaximumTest.java

Currently, we do not support proxy receiving PUB-ACK requests, which will cause the proxy to fail to receive message acknowledgements.
Then, all consumers will slowly not receive messages.
- Support ``PUB-ACK``

[Proxy] Support Proxy ``PUB-ACK``

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ClientReceiveMaximumTest.java

#528  Support MQTT Proxy ``PUB-ACK``,  but if user use topic name like ``abc/def`` the broker will get exception:
```java
2022-03-17T05:28:46,766+0000 [mqtt-redirect-io-67-8] ERROR io.streamnative.pulsar.handlers.mqtt.MQTTCommonInboundHandler - Exception was caught while processing MQTT message,
java.lang.IllegalArgumentException: Invalid short topic name 'bench/8453', it should be in the format of <tenant>/<namespace>/<topic> or <topic>
at org.apache.pulsar.common.naming.TopicName.<init>(TopicName.java:117) ~[org.apache.pulsar-pulsar-common-2.9.1.jar:2.9.1]
at org.apache.pulsar.common.naming.TopicName.<init>(TopicName.java:36) ~[org.apache.pulsar-pulsar-common-2.9.1.jar:2.9.1]
at org.apache.pulsar.common.naming.TopicName$1.load(TopicName.java:59) …
```

Fix MQTT proxy ``PUB-ACK`` topic with slash.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5TestTopicAutoCreation.java

Fixes #540
Master Issue: 540
The current auto-create topic is just affected by broker configuration, this PR support can be affected by namespace policy.
- Add logic that gets policy to determine whether to automatically create a topic.

Support auto create topic affects by namespace policy.

---

README.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/MqttV5AckHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/ConnectEvent.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

Master Issue: #409
As #560 has introduced system topic, this patch is supporting unique client id in MoP cluster.
Update related doc together.

Support unique client id in MoP cluster.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java

According to #409, if a client connects with the same client ID, we will close the previous one.
In MQTT5, we can send a ``disconnect`` message to the client to avoid reconnection.
- Support sends a disconnect message to the client when force delete.

Support broker send disconnect message to client.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java

Fixes #520 
Master Issue: #520 
When protocol handler close, MoP should close gracefully.

Close MoP resource when protocol handler close.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java

Relative issue #579 
The connection will throw NPE when the connection doesn't init complete then to invoke close.
Relative code as below:
https://github.com/streamnative/mop/blob/9022ce42ecfde5d63706f9ecbe7de2bcc92e5d06/mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java#L91-L108
https://github.com/streamnative/mop/blob/9022ce42ecfde5d63706f9ecbe7de2bcc92e5d06/mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java#L156-L173
When thread A creates a connection, just after invoking the `this.manager.addConnection(this)` method, thread B gets this connection and invokes the `close` method, which will throw NPE because the listener is not initialized.
- Move `this.manager.addConnection(this)` method to end of the constructor.

Fix NPE caused by the connection doesn't init complete then invoke close.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos2PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/QosPublishHandlersImpl.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/RetainedMessageHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/WillMessageHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/MqttEventUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/RetainedMessageEvent.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/RetainedMessage.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

Fix #250.
Support retained message semantics in standalone and cluster.
In standalone mode, the retained message is stored in the memory, which means it may lose data when the broker restart.

Support retained message semantics.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTConnectionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/TopicSubscriptionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java

Fixes #579 
Master Issue: #579
Based on issue #579, I found we exist a problem.
The `Connection#close` method is called multiple times when the previous connection is overwritten and closed by the `client id`, and some errors are thrown when it triggers a race condition.
- Changed all connection close actions to `channel#close` to trigger `channelInactive`, which then calls `Connection#close` to clean up data.
- Fix issue #579 by stopping connection 1 reconnecting and quickly cleaning up `subscriptionManager` to avoid duplicate subscriptions.

Change ``connection`` close logic to fix some potential probelms.

---

README.md
docs/mop-configuration.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/ConfigurationCompatibilityTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TLSTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTLSTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

The current MoP broker/proxy TLS use Apache Pulsar parameters, users can't set pulsar and MoP TLS separately.
- Move TLS part configuration with mqtt prefix. e.g: `tlsAllowInsecureConnection` to `mqttTlsAllowInsecureConnection`.
Use the `getXX` method to be compatible with the old configuration.

Provide separate TLS parameters for MoP

---

README.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAdditionalServlet.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServiceServlet.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/psk/PSKConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/psk/PSKSecretKey.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/psk/PSKUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/EventType.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/MqttEventUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/PSKEvent.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

Fixes #162 
Master Issue: #162
Currently, PSK identities are configured when MoP startup. If adding new identities, we have to restart the server, but new clients with new identities are a common scenario, so support adding PSK identities with REST API dynamically.

Support adding PSK dynamically

---

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

In PR #584 we introduce new servlet path from `mop-stats` to `/mop/*`
- Change test servlet path.

Fix wrong servlet path in test

---

README.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TLSTest.java

Current the MoP broker use TLS to rely on Pulsar deprecated configuration `tlsEnabled`, we should separate TLS configuration for MoP and Pulsar for flexibility.
- Deprecate TLS rely on Pulsar `tlsEnabled` configuration. use `mqttListeners` prefix instead of it. 

Deprecate TLS rely on Pulsar `tlsEnabled` configuration.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/ConfigurationUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyToPulsarTlsTest.java

The broker lookup handler could not resolve the addresses of multiple MQTT listeners. Because we used to use hard code to parse `mqttBrokerUrl`. we just assume it's a single URL. But this property can be multiple, like `mqtt://127.0.0.1:1884,mqtt+ssl://127.0.0.1:1885`
- Support `LookupHandler` to resolve multiple addresses.
- Support Proxy inner client use TLS.

Support Proxy `PulsarClient` connect to Broker with TLS

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterMessage.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

Master Issue: #592
As #588 merged, the proxy to broker will create at least one channel. If sending data is to fast, the channel will be not writable. so add `maxPendingSendRequest` to limit client side seding rate.
- Add `maxPendingSendRequest`
- Make proxy to re-use the adapter msg to avoid creating new one.
- ProxyTest#testBacklogShouldBeZeroWithQos0 will cover this patch.

Add maxPendingSendRequest to limit client side sending rate.

---

pom.xml

Currently, the pulsar-broker has a conflict dependency problem https://github.com/apache/pulsar/issues/15290. This will cause failure when building the project. And we need to resolve the dependency problem in Pulsar, after Pulsar fixes the problem, we could improve this change.
Exclude the grpc-related package from pulsar-broker.

Exclude grpc-related packages from pulsar-broker

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java

Current, when the broker sends a `DISCONNECT` message to the proxy, the proxy will close the channel and trigger `processConnectionLost`,  then the proxy will re-send a `DISCONNECT` message to the broker. 
This is wrong behaviour. when the broker sends a `DISCONNECT` message to the proxy, it means that the broker just wants the proxy to close the client's connection, and the broker has cleaned up the relevant state.
- When the proxy receives a `DISCONNECT` message from the broker, do not trigger the handler to resend `DISCONNECT` to the broker.
- Fixed NPE with null connection when processor invokes `processConnectionLost`.

Fix wrong behaviour when broker sends `DISCONNECT` message to proxy.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ClientRestrictions.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java

Master issue: #369
Support mqtt5 connect maximum packet size property.

Support mqtt5 connect maximum packet size property.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MessageBuilder.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/WillMessage.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java

Support MQTT5 last will message with user properties.

Support mqtt5 last will message with user properties.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5BatchMessageTest.java

Fixes #633
Master Issue: #633
See #633 to get the details.
- Fix the wrong logic for giving packet id.
- Add a new test to cover this change.

Fix give batched messages wrong packet id.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttPubAck.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ClientRestrictions.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5AuthorizationReasonCodeOnAllAckTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5AuthorizationProxyReasonCodeOnAllAckTest.java

See the tracker: #369
- Support MQTT-5: Request problem information

Support MQTT-5: Request problem information

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5PublishRelatedProtocolTest.java

Support send MQTT-5 message with user properties.

Support MQTT-5 Publish with user properties.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Constants.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5PublishRelatedProtocolTest.java

Support publish with `Content type`, `Correlation data`, `Response topic` properties.

Support MQTT-5 publish related properties.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/WillMessage.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ConnectRelatedProtocolTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5PublishRelatedProtocolTest.java

Support MQTT-5 Will Message with `Content type`, `Correlation data`, `Payload format indicator`, `Response topic`
Publish message with `Payload format indicator`

Support MQTT-5 will message with properties.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ClientRestrictions.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5PublishRelatedProtocolTest.java

Support MQTT-5 publish message with message expiry interval.

Support MQTT5-5 publish message expiry interval.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/WillMessageHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/WillMessage.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ConnectRelatedProtocolTest.java

Master Issue: #369 
Support MQTT-5 will message with message expiry interval and delay interval.

Support MQTT-5 will message with message expiry interval and delay interval

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttConnectAck.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttUtils.java

Master Issue: #369 
Support MQTT-5 ConnectAck with Max Qos and response information.

Support MQTT-5 connect ack with Max Qos.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttConnectAck.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ServerRestrictions.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java

Master Issue: #369 
Support MQTT-5 Conn-ACK with `subscriptionIdentifiersAvailable` and `maximumPacketSize`

Support MQTT-5 Conn-ACK with `subscriptionIdentifiersAvailable` and `maximumPacketSize`

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/QosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos2PublishHandler.java

Fixes #<xyz>
when we start two client connections, and the proxy connection pool size is set to 1, Qos1Publisher will get wrong connection.
we can pass the connection from Processor to QosPublisher.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …

#Fix publish request get wrong connection when shared connection

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttConnectAck.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/restrictions/ClientRestrictions.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java

Support MQTT-5 property `topicAliasMaximum`
- Support MQTT-5 property `topicAliasMaximum`
*(or)*
*(or)*
*(example:)*

Support MQTT-5 property `topicAliasMaximum`

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/QosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos2PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/QosPublishHandlersImpl.java

Moved `QosPublishHandlers` to `MQTTService` to avoid creating handlers on each handler.
- Move `QosPublishHandlers` into `MQTTService`
*(or)*
*(or)*
*(example:)*

Move `QosPublishHandlers` into `MQTTService`

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/TopicAliasManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/MQTTTopicAliasExceedsLimitException.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/MQTTTopicAliasNotFoundException.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java

Support MQTT-5 topic alias. See specification https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html
- Support topic alias.
*(or)*
*(or)*
*(example:)*

Support MQTT-5 topic alias.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAuthenticationService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttConnectAck.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/BasicAuthenticationTest.java

Support MQTT-5 CONN with Auth-Data and Auth-Method.

Support MQTT-5 CONN Auth Method and Auth Data.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAuthenticationService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/mqtt5/Mqtt5DisConnReasonCode.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/BasicAuthenticationTest.java

Master Issue: #369 
Support MQTT-5 Auth command.

Support MQTT-5 Auth command.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAuthenticationService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java

When we try to use Oauth2 to verify Authorization, we have to pass the token to
Authorisations Provider, but current, we just passed the role.
- Save the original authentication data to `Connection` and use it for the authorisation check.

Use Original Authentication data to do Authorization.

---

README.md
docs/mop-configuration.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java

Our proxy port is in conflict with AoP, We can change it to another one.
- Make proxy port from 5682 to 5678
- Make proxy SSL port from 5683 to 5679
- Make proxy psk port from 5684 to 5680

Change proxy default port

---

README.md
docs/mop-configuration.md
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java

As it's the default port, even if it conflicts with AoP, users can change it to other ports.
Reverts streamnative/mop#712

Revert "Change proxy default port"

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTSubscriptionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/psk/PSKConfiguration.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/base/CleanSessionTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5CleanStartTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5SessionExpireIntervalTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5SessionExpireIntervalTest.java

Pulsar broker used collections4 instead of collections and mop also need to use collections4.
https://github.com/apache/pulsar/pull/16209
Change collections to collections4

Use collections4 instaed of collections

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java

When the broker hangs or closes, if the client just executes the lookup request, the client will fail, so adding retriable topic lookup.
*(or)*
*(or)*
*(example:)*

Support lookup broker retriable

---

pom.xml

When i compile on jdk11 and just got the error (Note: pom.xml still configuration for 1.8 )  of `module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module ...` , 
```shell
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pulsar-protocol-handler-mqtt: 
Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$Di
scoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.to
ols.javac.processing" to unnamed module @1d071d30 -> [Help 1]
```
Upgrade lombok version to 1.18.22

Upgrade lombok to 1.18.22

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTServerConfiguration.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarMessageConverter.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MessageConverTest.java

1. Support fill  pulsar message eventtime from mqtt properties or auto fill when convert pulsar message 
2. Support fill pulsar message key from mqtt properties
1. Add configuration for auto fill eventtime, false by default.
2. Add configuration for fill eventtime from properties.
3. Add configguration for fill message key from properties.
- Added integration tests for message conver 

Support eventtime and  message key

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/AutoSubscribeHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenterImpl.java

1. When subscribing to MoP, we will create too many unused `AutoSubscribeHandler` listeners to the event store, for the performance problem, We can change this behaviour to being lazy.
2.  Avoid using metadata-thread to invoke logical operations.
- Lazy register `AutoSubscribeHandler`
- Use `OrderedExecutor` to avoid the concurrent problem.

Lazy init listener and avoid use metadata-thread run task.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/MQTTEventSystemTopicClient.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java
pom.xml

Upgrade to depend on 3.0.0.1-SNAPSHOT
* Upgrade pulsar version to 3.0.0.1-SNAPSHOT
* Upgrade netty version to 4.1.89.Final
*(or)*
*(or)*
*(example:)*

Upgrade to depend on 3.0.0.1-SNAPSHOT

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java

Fixes  #924
This fixes the issue of retain messages never making it to the destination pulsar topic. The issue seems to originate from the fact that adding a retain message seemed to completely evade the `writeToPulsarTopic` method, which effectively breaks retained MQTT messages from ever getting sent through as expected.
All retained messages are now also written into their respective pulsar topics per the expected behavior, which should now mimic every other MQTT broker's behavior.
- Run MoP
- Subscribe to topic
- Publish retained message, should see message on subscription
- Unsubscribe and …

Write retained messages to pulsar topic

---

mqtt-impl/pom.xml
pom.xml
tests/pom.xml

Bump MoP version to 2.9.5.1
- Bump MoP version to 2.9.5.1
*(or)*
*(or)*
*(example:)*

Bump MoP version to 2.9.5.1

---

pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java

1. Upgrade mqtt-codec to 4.1.94 to match the netty version.
2. Remove the useless mock
3. Add grpc dependency to avoid StackOverFlow
```
Exception in thread "main" java.lang.StackOverflowError
at org.eclipse.aether.util.graph.transformer.ConflictResolver$ConflictContext.isIncluded(ConflictResolver.java:1059)
at org.eclipse.aether.util.graph.transformer.NearestVersionSelector$1.accept(NearestVersionSelector.java:154)
at org.eclipse.aether.util.graph.visitor.PathRecordingDependencyVisitor.visitEnter(PathRecordingDependencyVisitor.java:102)
at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:343)
at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:347)
at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode …
```

Upgrade mqtt-codec 4.1.94

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java

Add cache for the event writer to avoid creating event writer every time.
*(or)*
*(or)*
*(example:)*

Add Cache for event writer.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java

Change the log level to debug to avoid tons of logs.
- Change the log level to debug to avoid tons of logs.

Change log level to debug

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java

Fix `IllegalReferenceCountException` exception to break the future callback. 
The exception stack trace is as follows:
```
2023-07-27T00:43:58,769+0000 [mqtt-proxy-adapter-80-2] ERROR io.streamnative.pulsar.handlers.mqtt.adapter.AdapterChannel - [AdapterChannel] Proxy write to broker poc-use1-broker-1.poc-use1-broker-headless.o-xj8il.svc.cluster.local/240.240.0.4:1
883 message [!!!io.streamnative.pulsar.handlers.mqtt.adapter.MqttAdapterMessage@b720745=>io.netty.util.IllegalReferenceCountException:refCnt: 0!!!] failed.
java.util.concurrent.CompletionException: io.netty.channel.StacklessClosedChannelException
at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
at …
```

Fix `IllegalReferenceCountException` exception to break the callback

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/ack/MqttPubAck.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyIntegrationTest.java

Fix the lookup issue.  this pr only fix this issue for Qos1 under MQTT-5.
```
2023-07-25T08:27:12,754+0000 [pulsar-2-1] ERROR io.streamnative.pulsar.handlers.mqtt.support.MQTTBrokerProtocolMethodProcessor - [Publish] [bench/mqtt/4296] Write MqttPublishMessage[fixedHeader=MqttFixedHeader[messageType=PUBLISH, isDup=false, qosLevel=AT_MOST_ONCE, isRetain=false, remainingLength=274], variableHeader=MqttPublishVariableHeader[topicName=bench/mqtt/4296, packetId=-1], payload=PooledSlicedByteBuf(ridx: 0, widx: 256, cap: 256/256, unwrapped: PooledUnsafeDirectByteBuf(ridx: 277, widx: 277, cap: 277))] to Pulsar topic failed.
org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: Namespace bundle for topic (persistent://public/default/bench%2Fmqtt%2F4296) not served by …
```

Fix lookup issue for MQTT-5

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java

```
2023-07-27T09:04:27,927+0000 [pulsar-ph-mqtt-51-1] ERROR io.streamnative.pulsar.handlers.mqtt.support.Qos1PublishHandler - [bench/mqtt/3482] Publish msg MqttPublishMessage[fixedHeader=MqttFixedHeader[messageType=PUBLISH, isDup=false, qosLevel=AT_LEAST_ONCE, isRetain=false, remainingLength=276], variableHeader=MqttPublishVariableHeader[topicName=bench/mqtt/3482, packetId=65], payload=PooledSlicedByteBuf(ridx: 0, widx: 256, cap: 256/256, unwrapped: PooledUnsafeDirectByteBuf(ridx: 279, widx: 279, cap: 279))] fail.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Namespace bundle public/default/0x203b5d0d_0x40000000 is being unloaded
at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
at …
```

Fix bundle is being unload IllegalState exception

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java

Cherry-pick #1041 
Fix `IllegalReferenceCountException` exception to break the future callback. 
The exception stack trace is as follows:
```
2023-07-27T00:43:58,769+0000 [mqtt-proxy-adapter-80-2] ERROR io.streamnative.pulsar.handlers.mqtt.adapter.AdapterChannel - [AdapterChannel] Proxy write to broker poc-use1-broker-1.poc-use1-broker-headless.o-xj8il.svc.cluster.local/240.240.0.4:1
883 message [!!!io.streamnative.pulsar.handlers.mqtt.adapter.MqttAdapterMessage@b720745=>io.netty.util.IllegalReferenceCountException:refCnt: 0!!!] failed.
java.util.concurrent.CompletionException: io.netty.channel.StacklessClosedChannelException
at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.jav …
```

Fix IllegalReferenceCountException exception to break the callback

---

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java

```
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
- with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.
```

Fix mock object

---

pom.xml
tests/pom.xml

Upgrade log4j2 version and exclude other dependency log to fix many logging bindings.
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/tboy/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/tboy/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
```
*(or)*
This change is already covered by existing tests, such as …

Upgrade log4j2 version

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java

```
org.apache.pulsar.broker.PulsarServerException: java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.broker.systopic.SystemTopicClient$Reader.closeAsync()" because "this.reader" is null
at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:583)
at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:373)
at io.streamnative.pulsar.handlers.mqtt.mqtt5.hivemq.proxy.MQTT5ProxyIntegrationTest.testBrokerThrowServiceNotReadyException(MQTT5ProxyIntegrationTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) …
```

Fix close reader NPE.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java

Revert #1047, as it breaks the original logic in the broker .
The broker will add `addIdleStateHandler` according to user configed keepalive-time dynamically.
If #1047 doesn't send a ping request to the broker, the broker will close the client connection due to idle handler.
The ProxyTest#testProxyProcessPingReq will help cover this case.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

Revert "Add ping request for adapter channel (#1047)"

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTSubscriptionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java

Fixes #954
Resubscribing was causing clients to be disconnected for duplicate subscription even though the subscription had been unsubscribed. The MQTTSubscriptionManager never removed subscriptions for a client, thus if you resubscribed on a topic it would always be a duplicate even if you unsubscribed previously.
MQTTSubscriptionManager now implements a way to remove a subscription by topic for a given client. The `processUnsubscribe` method now invokes that to appropriately remove the subscriptions on unsubscribe.
This change is already covered by existing tests

remove subs from subscription manager on unsubscribe

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/WillMessageHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemEventService.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java

Fixes #937
LWT did not function as expected. LWTs mechanism would utilize the system topic to propagate fireWillMessage events, and then each MoP instance would look at each of it's subscriptions on the topic the LWT should be published on, it would then send the LWT to all these susbcriptions directly. This meant LWT did NOT reach Pulsar topics, nor did QoSPublishHandlers come into play at all for LWT which means that retained LWTs did not work.
Instead of using the system topic I changed WillMessageHandler to publish the messages to their destination pulsar topic. This means that both Pulsar and MQTT clients can receive these messages, as MoP already subscribes on the pulsar topic on behalf of the MQTT MoP connection. WillMessageHandler now acquires the QoSPublishHandlers from …

change last will to publish to puslar, remove LWT events as they're no

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java

Fixes #1210
When running with TLS disabled `PulsarServiceLookupHandler::isLookupMQTTBroker` is calling `localBrokerData.getPulsarServiceUrlTls()` which returns `null` if TLS is disabled. This method then tried to call `equals(..)` on the returned value which is `null` causing a `NullPointerException`. This prevents MoP proxy from working properly, as it will never resolve the host and this loop will simply crash.
Instead of calling `equals` on the values returned from `localBrokerData`, which can be `null` if missing in the metadata store, I instead call `equals` on the strings created which are compared against since those will never be null, but it's safe to pass null as an argument to `String::equals`. This prevents the …

call equals on formatted strings since they will never be null

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTSubscriptionManager.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java

The fix of #957 cause `MQTT5ReasonCodeOnAllACKTest` fails
https://github.com/streamnative/mop/actions/runs/7357019768/job/20027990799
*(or)*
*(or)*
*(example:)*

Fix unsubscribe topic cause the test failed.

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos0PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java
mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MessagePublishContext.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleBrokerEnableDedupTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java

When the broker enable dedup, the client will publish msg failed due to not set producerName.
```
20:18:21.791 [pulsar-ph-mqtt-36-1:io.streamnative.pulsar.handlers.mqtt.support.MQTTBrokerProtocolMethodProcessor@199] ERROR io.streamnative.pulsar.handlers.mqtt.support.MQTTBrokerProtocolMethodProcessor - [Publish] [a/b/c] Write MqttPublishMessage[fixedHeader=MqttFixedHeader[messageType=PUBLISH, isDup=false, qosLevel=AT_MOST_ONCE, isRetain=false, remainingLength=17], variableHeader=MqttPublishVariableHeader[topicName=a/b/c, packetId=-1], payload=UnpooledSlicedByteBuf(ridx: 0, widx: 10, cap: 10/10, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf(ridx: 19, widx: 19, cap: 8192))] to Pulsar topic failed.
java.lang.NullPointerException: Cannot invoke …
```

Fix broker enable dedup cause client publish msg NPE

---

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java

`new ExecutorProvider(proxyConfig.getLookupThreadPoolNum(), "mop-lookup-thread") ;`
It will create a FinalizableDelegatedExecutorService
`(ScheduledExecutorService) executorProvider.getExecutor();`
It can't be cast to a ScheduledExecutorService, and it will create a RuntimeException without catch, which is also blocking the proxy thread

fix a ClassCastException when scheduling to look up

---

mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/channel/MQTTServerCnx.java
mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/impl/consumer/MessagePublishContext.java
mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/qos/AbstractQosPublishHandler.java
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleBrokerEnableDedupTest.java

Fix broker enable dedup cause client publish failed

---

mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java
mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/channel/MQTTProxyAdapter.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …

Make the proxy adapter worker thread configrable

---

.github/workflows/pr_test.yml

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
*(or)*
*(or)*
*(example:)*
(If you need help on updating docs, create a doc …

Upgrade artifact github action version

---

mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/channel/AdapterChannel.java
mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/channel/MQTTProxyAdapter.java
mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/impl/MQTTProxyProtocolMethodProcessor.java
tests/pom.xml
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/paho/proxy/TestProxyConnectMultiBroker.java

When client uses the same connection to subscribe many topics, the mop proxy will create multi connections to the target broker. If some of the channel(proxy to broker) has no msg, the channel will be closed due to inactive event. In this case, the mop proxy could close the only one connection. and cause the client to be in a wrong behavior.
`TestProxyConnectMultiBroker` could reproduce this issue.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large …

Fix proxy conn multi broker

---

pom.xml

We will use github private maven repository widely in the future including streamnative/pulsar's.
It is convenient to use wildcard repository url to match all the maven packages of SN org.

Use Github package wildcard repository url

---

mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/MQTTConnectionManager.java
mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/systemtopic/SystemTopicBasedSystemEventService.java
mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/web/admin/Devices.java

Fixes #<xyz>
```java
2025-04-29T14:35:42,091+0000 [broker-client-shared-internal-executor-5-1] ERROR io.streamnative.pulsar.handlers.mqtt.common.systemtopic.SystemTopicBasedSystemEventService - refresh cache error
java.lang.NullPointerException: null
at java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:?]
at java.base/java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:?]
at io.streamnative.pulsar.handlers.mqtt.common.MQTTConnectionManager$ConnectEventListener.onChange(MQTTConnectionManager.java:129) ~[?:?]
at io.streamnative.pulsar.handlers.mqtt.common.systemtopic.SystemTopicBasedSystemEventService.lambda$refreshCache$14(SystemTopicBasedSystemEventService.java:240) ~[?:?]
at …
```

Fix connection event error

---

README.md

Add support MQTT5 features related doc

---

mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/MQTTCommonInboundHandler.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MessageConverTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java

Currently, when there is an exception in checking the connect message, we directly close the channel. However, the client might keep retrying indefinitely. It's best for us to return a connection error to the client.
For CONNECT message errors, send a CONNACK error response then close channel.
For other message errors, send a DISCONNECT error response if supported then close channel.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

Fix MQTT message error handling and improve connection responses
