streamnative/mop

pom.xml
Signed-off-by: xiaolong.ran <rxl@apache.org>
Upgrade pulsar version to 2.6.2.0.
=> Upgrade pulsar version to 2.6.2.0

scripts/set-pulsar-version.sh
Signed-off-by: xiaolong.ran <rxl@apache.org>
Add scripts of set-pulsar-version for repo.
=> Add scripts of set-pulsar-version for repo

.github/workflows/pr_test.yml, mqtt-impl/pom.xml, pom.xml, tests/pom.xml
weekly release verify 2.7.1.1-rc-202103251930
=> weekly release verify 2.7.1.1-rc-202103251930

mqtt-impl/pom.xml, pom.xml, tests/pom.xml
=> bump pulsar to `2.7.1.1`

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/ProtocolMethodProcessorImpl.java, pom.xml
Bump MQTT version to `4.1.66.Final`
=> Bump MQTT version to `4.1.66.Final`

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/ProtocolMethodProcessorImpl.java
=> Fix qos1 pubAck action is not executed forever when log level is not debug

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/ProtocolMethodProcessorImpl.java
###Motivation
Cherry pick master branch #89 to this branch.
=> [Cherry pick] Fix qos1 pubAck action is not executed forever when log level is not debug.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Constants.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/LookupHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyInboundHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/ProxyService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/ProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java
- Close proxy service when close protocol handler.
- Fix typo.
- Fix log level.
- Replace checkState with checkArgument.
- Regular constant field naming.
- Rename clientId to attachClientId.
=> Close proxyService when close protocol handler

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
When execute `processConnect` in proxy, it's not the same like DefaultProtocolMethodProcessorImpl to add connection
like below:
`ConnectionDescriptorStore.getInstance().addConnection(descriptor)`.
So when executing `processDisconnect`, we should directly transfer the command to broker and then close broker and client channel.
=> Remove ConnectionDescriptor from processDisconnect.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
MQTTProxyHandler has delegated all the commands to be execute by MQTTProxyProtocolMethodProcessor. So it's better to move 
`increaseSubscribeTopicsCount`, `decreaseSubscribeTopicsCount` to MQTTProxyProtocolMethodProcessor.
=> Move SubscribeTopicsCount related methods from MQTTProxyHandler to MQTTProxyProtocolMethodProcessor

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java, mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/PulsarTopicUtilsTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/BasicAuthenticationIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/TLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/hivemq/HiveMQIntegrationTest.java
=> Fix topic name and add test case. 

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
Before this patch, when proxy executes `publish/subscribe/unsubscribe` command, we init MQTTProxyExchanger and use a single label `brokerFuture` to indicate the connAck state.  `brokerFuture` is not accurate by naming. 
We should name `brokerConnected` to represent `the channel has connected` and add `brokerConnectedAck` to represent `the channel has received connect ack response`.
When the exchanger has `connctedAck`, we can dispatch `publish/subscribe/unsubscribe`.
=> Init MQTTProxyExchanger with CompletableFuture and add connAck state.

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/BasicAuthenticationIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/TLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/TokenAuthenticationIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/hivemq/HiveMQIntegrationTest.java
The MQTT proxy should connect more than one broker to do more distributed and integration test.
So we'd better refactor the test cases, especially the `MQTTProtocolHandlerTestBase.java` class.
- Refactor MQTTProtocolHandlerTestBase.java
- Remove some duplicated/unused codes.
=> Refactor the test case.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Constants.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java
Netty channel attr can use to store any data that bind to this channel. So we can use this feature to store connect msg and do not need to use List anymore.
- Bind connect msg to channel attr.
- Remove List to store that.
=> Attach connect msg to channel.

README.md, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/ConfigurationUtils.java, mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/ConfigurationUtilsTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
=> Support mqtt broker TLS-PSK.

.github/workflows/pr_test.yml, scripts/retry.sh
MoP has flaky test, it's better to add retry logic.
- Add retry script to enable retry when test fails, max retry to 5 times.
=> Add retry script

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
=> Fix subscribe to multi-topics lost message issue

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
=> Fix subscribes to multiple topics, and sends multiple heartbeat packets

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/ProxyTest.java
=> Add test for pub and sub with different topics in proxy.

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/SimpleIntegrationTest.java
=> Add test for subscribing many times.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Constants.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/WillMessage.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java
add will message for the broker side
=> Support will message semantic

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_request.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR for issue #235
- bug_report
- enhancement_request
- feature_request
=> [ Project ] Add issue template for mop.

.gitignore
When i test project in local, i found a lot of new file in unpacked nar. 
I think we need to ignore these files.
=> [  Project  ] Add ignore item .

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Constants.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/MqttUnsubAckReasonCode.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/package-info.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttUtils.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/MQTT5IntegrationTest.java
- enhance unsubAck message.
By enhancing the unsuback message, MQTT5 can be basically supported.
=> MQTT5 - Support UnSubAck response

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MQTTSubAckMessageUtils.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/MqttSubAckReasonCode.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/MQTT5ReasonCodeOnAllACKTest.java
support subscribe request sub-ack.
=> MQTT5 - Support subscribe request sub-ack

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/AbstractQosPublishHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MQTTPubAckMessageUtils.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/codes/MqttPubAckReasonCode.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/MQTT5ReasonCodeOnAllACKTest.java
=> MQTT5 - Support pub-ack

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttConnAckMessageHelper.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/CleanSessionTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/MQTT5CleanStartTest.java
- mqtt3 clean session
- mqtt5 clean start
=> Support clean session

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/AuthorizationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/BasicAuthenticationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/CleanSessionTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/TokenAuthenticationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/AuthorizationProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/BasicAuthenticationProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/TokenAuthenticationProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/psk/PSKClient.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/base/HiveMQIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5AuthorizationReasonCodeOnAllAckTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5CleanStartTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ClientUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReasonCodeOnAllACKTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5AuthorizationProxyReasonCodeOnAllAckTest.java
- refactor integration test structure.
=> Refactor test structure.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ClientUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ReceiveMaximumTest.java
relate issue #301
- Support client receive maximum feature.
=> Support client receive maximum feature

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/exception/handler/MqttPubExceptionHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/factory/MqttConnAckMessageHelper.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/Qos1PublishHandler.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ClientReceiveMaximumTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5ServerReceiveMaximumTest.java
- user can config server receive maximum.
- server side receive maximum just limit QOS > 0.
- server receive maximum default value is 65535.
=> Support Server side receive maximum.

.github/ISSUE_TEMPLATE/flaky_test.md
Motivation 
see issue #329
Modification
Add flaky test template.
=> Add flaky test template.

README.md
Add missing config doc about MoP HTTP metrics.
=> Add doc for mop http metrics.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java
There is too much log if authorization is disabled.
Change log level.
*If `yes` was chosen, please highlight the changes*
- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)
Check the box below and label this PR (if you have committer privilege).
=> There is too much log if authorization is disabled.

.github/ISSUE_TEMPLATE/mip.md
We need MIP to regulate our process of proposing new features.
- Add Github MIP template.
=> Add MIP tempalte

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTInboundHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyExchanger.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyInboundHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/AbstractCommonProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AbstractAckHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/handler/AckHandler.java
This is related #365 .
#365 has only fix the release about broker side, this is for proxy side.
=> Fix proxy not release buf.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyException.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java
Refactor the complex code of the proxy "subscribe" command to reduce the method calls for releasing the reference counted object.
- Refactor ``PulsarTopicUtils#asyncGetTopicsForSubscribeMsg``  to not return null.
=> Refactor the complex code of the proxy "subscribe" command to reduce the method calls for releasing the reference counted object.

README.md
##Motivation
As @mattisonchao has pushed 23 commits with 7000 lines + codes, we decide to make him as MoP maintainer.
=> Add maintainer

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/TopicSubscriptionManager.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/NettyUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5CleanStartTest.java
relate issue #384
Because of many logic about topic subscription everywhere, this may easy to cause error.
I think we need to extract topic subscription logic to ``TopicSubScriptionManager``.
- Extract topic subscription logic to ``TopicSubScriptionManager``.
- This change can Fix #384.
=> Extract topic subscription logic to ``TopicSubScriptionManager``

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
=> Fix NPE when connect method authentication fail.

mqtt-impl/pom.xml, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java, pom.xml, tests/pom.xml, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
Bump pulsar version 2.10.0.0 rc3
=> Bump pulsar version 2.10.0.0 rc3

mqtt-impl/pom.xml, pom.xml, tests/pom.xml
Now the branch 2.8.2 is behind the latest version, So we need to update it.
- Bump version to 2.8.2.10
=> [Branch 2.8.2] Bump version to 2.8.2.10

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
See #497
- Move lookup logic into connecting broker logic to avoid lookup every time.
=> Fix many lookup request when use proxy.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTProtocolHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/ConfigurationUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
#504  ci build fail .
it because  in unit test case the 'properties' field of  MQTTServerConfiguration  is incomplete。 
so i think that  we should create property config to imitate loading real broker config
=> alter unit test config 

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
Fixes #484
Master Issue: #484
Check channel state before sending the message.
=> Check channel active state before send.

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Add test to coverage topic unload and for #538 .
=> [Test] Add test to coverage topic unload and issue #538.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTNamespaceBundleOwnershipListener.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTTopicOwnershipListener.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/base/SimpleIntegrationTest.java
Fixes #531
Add NamespaceBundleOwnershipListener to help troubleshoot problems.
=> Support NamespaceBundleOwnershipListener.

.github/workflows/pr_test.yml, README.md, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/WillMessageHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/DisabledSystemEventService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/EventType.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/LastWillMessageEvent.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemEventService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/systemtopic/SystemTopicBasedSystemEventService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/WillMessage.java, pom.xml, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
As #560 has introduced system topic, this patch is supporting last will message in MoP cluster.
Doc is also updated in this patch.
=> Support last will message in cluster

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/MqttPropertyUtils.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/properties/PulsarProperties.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/messages/properties/package-info.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/DefaultProtocolMethodProcessorImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenterImpl.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyIntegrationTest.java
see #562 
- Support proxy side dynamic subscribe new topic by the filter.
=> Support proxy side dynamic subscribe new topic by the filter.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterEncoder.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MqttAdapterMessage.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/FutureUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTLSTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java, tests/src/test/resources/log4j2.xml
After #588 , MqttAdapterMessage will write and flush, it's not released when sending to the client.
- Release pub msg after encoder.
=> Fix send message to consumer not release buf bug.

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/AdapterChannel.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTServerCnx.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/AdapterChannelTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/MqttProxyAdapterTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Fixes #591
See #591
- Support proxy connection pool
=> Support proxy connection pool

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
If the client subscribes to many topics, when it disconnects, the proxy will send the `Disconnect` message to the broker multiple times.
-  Deduplicate the same broker channel.
=> Fix send `Disconnect` message many times from proxy to broker

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenterImpl.java
See #624 
- Use `CopyOnWriteArrayList` instead of `synchronizedList`
=> Fix race condition casing NPE

.github/workflows/pr_test.yml, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java, pom.xml
=> Upgrade to build with JDK17

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTChannelInitializer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyChannelInitializer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTConsumer.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/PulsarTopicUtils.java, pom.xml, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
Upgrade to depend on pulsar-2.11
=> Upgrade to depend on pulsar-2.11

pom.xml
Fix repository conflict with weekly release.
=> Fix conflict with weekly release

pom.xml
Bump Netty version to 4.1.93.Final 
- Bump Netty version to 4.1.93.Final
*(or)*
*(or)*
*(example:)*
=> Bump Netty version to 4.1.93.Final

mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTMetricsCollectorTest.java, mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTMetricsProviderTest.java, mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/ConfigurationUtilsTest.java, mqtt-impl/src/test/java/io/streamnative/pulsar/handlers/mqtt/untils/MqttMessageUtilsTest.java, pom.xml
=> Remove grpc dependency

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/hivemq/base/CleanSessionTest.java
1. Fix connection timeout ms.
2. Fix flaky test.
*(or)*
*(or)*
*(example:)*
=> Fix connection timeout ms

.ci/Dockerfile, .github/workflows/dispatch-build-test-image.yaml, pom.xml
Support fast-build docker images with existing pulsar images.
=> Support fast build docker image

.ci/Dockerfile, .github/workflows/dispatch-build-test-image.yaml
Fix the dispatch docker image building.
- Fix the dispatch docker image building.
=> Fix dispatch docker build

mqtt-impl/pom.xml, pom.xml, tests/pom.xml
Bump the project & pulsar version to 2.10.4.6
=> Bump project & pulsar version to 2.10.4.6

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonInboundHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/ProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java
#1039 
- Add connection establish check.
=> Fix NPE cased by inflating message

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java
Improve log to avoid too much error
- Change the log level to warn
=> Improve log to avoid too much error

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MessagePublishContext.java
Fix publish latency unit.
- Fix publish latency unit.
=> Fix publish latency unit

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/adapter/MQTTProxyAdapter.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java
=> Add ping request for adapter channel

.github/workflows/ci-publish.yaml
Change the docker image name from mop to mqtt-perf.
- Change the docker image name from mop to mqtt-perf.
=> Change docker image name

.github/workflows/ci-publish-mqtt-perf.yaml, .github/workflows/ci-publish.yaml
Fix empty mqtt-perf docker image.
=> Fix empty mqtt perf image.

mqtt-impl/pom.xml, pom.xml, tests/pom.xml
Upgrade cluster version to 3.0.0.4
=> Upgrade pulsar verison to 3.0.0.4

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/PulsarServiceLookupHandler.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTServerCnx.java, pom.xml, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java
Update the pulsar version to 3.2.0 SNAPSHOT.
=> *: Update pulsar master version to 3.2.0 SNAPSHOT

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarEventCenterImpl.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/event/PulsarTopicChangeListener.java
Add filter system topic when using EventCenter.
Also fix https://github.com/streamnative/mop/actions/runs/7542822040/job/20533077407
=> Add filter system topic when using EventCenter

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTSubscriptionManager.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/base/MQTT5IntegrationTest.java
Fixes #954
- Add test for this fix.
=> Add test for resubscribe

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/Connection.java, tests/pom.xml, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/paho/proxy/ProxyIntegrationTest.java
Fixes #1212
In the issue regarding this issue I was asked to reproduce the issue with an integration tests. This PR provides an integration test which reproduces the issue reliably. Obviously tests will not pass as this provides a test case which reproduces a known issue.
=> Fix proxy keepalive issue

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTCommonConfiguration.java
Supported TLS gets the configuration protocol plug-in before Pulsar
=> Supported TLS gets the configuration protocol plug-in before Pulsar

pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Pin version of Jackson to avoid conflict with Pulsar 3.3

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
=> Fix test for 3.4.0-SNAPSHOT

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/identitypool/AuthenticationProviderMTls.java, pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Fix authentication metrics for 4.0

.github/workflows/pr_test.yml
=> Fix workflow 

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAuthenticationService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Fix mTLS authorization bug

mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/MQTTAuthenticationService.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyConfiguration.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/MQTTProxyProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/support/MQTTBrokerProtocolMethodProcessor.java, mqtt-impl/src/main/java/io/streamnative/pulsar/handlers/mqtt/utils/MqttMessageUtils.java
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Fix mTls authorize bug

.github/workflows/pr_test.yml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Update the workflow from v2 to v3

mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/channel/MQTTServerCnx.java, mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/Connection.java, mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/Constants.java
=> Fix the auth data is NPE error

mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/channel/MQTTBrokerInboundHandler.java, mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/processor/MQTTBrokerProtocolMethodProcessor.java, mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/qos/AbstractQosPublishHandler.java, mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/qos/MQTTProducer.java, mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/qos/QosPublishHandler.java, mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/qos/QosPublishHandlers.java, mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/qos/QosPublishHandlersImpl.java, mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/Connection.java, mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/channel/AdapterChannel.java, mqtt-proxy/src/main/java/io/streamnative/pulsar/handlers/mqtt/proxy/impl/MQTTProxyProtocolMethodProcessor.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/broker/AdapterChannelTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt3/fusesource/proxy/ProxyTest.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5ProxyIntegrationTest.java
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Fix mop producer publish metric

pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Remove yahoo dependency

.github/workflows/pr_test.yml, pom.xml, scripts/build.sh
Use SN bom to reduce image size and cve issues.
*(or)*
*(or)*
*(example:)*
=> Use SN bom

tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/base/MQTTProtocolHandlerTestBase.java
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Fix mock zookeeper change

.github/workflows/pr_test.yml
Remove jacoco upload jobs to make CI pass.
=> Remove jacoco upload jobs

mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/impl/PulsarMessageConverter.java, mqtt-common/src/main/java/io/streamnative/pulsar/handlers/mqtt/common/utils/MqttMessageUtils.java, tests/src/test/java/io/streamnative/pulsar/handlers/mqtt/mqtt5/hivemq/proxy/MQTT5AuthorizationProxyReasonCodeOnAllAckTest.java
Fixes #<xyz>
Fix user properties lost when enable authorization
*(or)*
*(or)*
*(example:)*
(If you need help on …
=> Fix user properties lost when enable authorization

mqtt-broker/src/main/java/io/streamnative/pulsar/handlers/mqtt/broker/impl/MQTTNamespaceBundleOwnershipListener.java
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
Check …
=> Fix listener error
